<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDQUWtJA\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDQUWtJA/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDQUWtJA.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDQUWtJA\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDQUWtJA\App_KernelTestDebugContainer([
    'container.build_hash' => 'DQUWtJA',
    'container.build_id' => 'c799a58b',
    'container.build_time' => 1685309743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDQUWtJA');
