<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'get_list_of_games' => [[], ['_controller' => 'App\\Controller\\GameController::getPartieList'], [], [['text', '/games']], [], [], []],
    'create_game' => [[], ['_controller' => 'App\\Controller\\GameController::launchGame'], [], [['text', '/games']], [], [], []],
    ' getGameInfo' => [['identifiant'], ['_controller' => 'App\\Controller\\GameController::getGameInfo'], [], [['variable', '/', '[^/]++', 'identifiant', true], ['text', '/game']], [], [], []],
    'add_user_to_game' => [['id', 'playerRightId'], ['_controller' => 'App\\Controller\\GameController::inviteToGame'], [], [['variable', '/', '[^/]++', 'playerRightId', true], ['text', '/add'], ['variable', '/', '[^/]++', 'id', true], ['text', '/game']], [], [], []],
    'send_choice' => [['identifiant'], ['_controller' => 'App\\Controller\\GameController::play'], [], [['variable', '/', '[^/]++', 'identifiant', true], ['text', '/game']], [], [], []],
    'delete_game' => [['id'], ['_controller' => 'App\\Controller\\GameController::deleteGame'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/game']], [], [], []],
    'liste_des_users' => [[], ['_controller' => 'App\\Controller\\UserController::getListeDesUsers'], [], [['text', '/users']], [], [], []],
    'user_post' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/users']], [], [], []],
    'get_user_by_id' => [['identifiant'], ['_controller' => 'App\\Controller\\UserController::getUserWithIdentifiant'], [], [['variable', '/', '[^/]++', 'identifiant', true], ['text', '/user']], [], [], []],
    'udpate_user' => [['identifiant'], ['_controller' => 'App\\Controller\\UserController::updateUser'], [], [['variable', '/', '[^/]++', 'identifiant', true], ['text', '/user']], [], [], []],
    'delete_user_by_identifiant' => [['id'], ['_controller' => 'App\\Controller\\UserController::suprUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
];
