<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMET6elu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMET6elu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMET6elu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMET6elu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMET6elu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MET6elu',
    'container.build_id' => '183dec48',
    'container.build_time' => 1685308466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMET6elu');
